name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create Firebase Config
        run: |
          echo "import { initializeApp } from 'firebase/app';
          import { getAnalytics } from 'firebase/analytics';
          import { getFirestore } from 'firebase/firestore';
          const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            measurementId: '${{ secrets.MEASUREMENT_ID }}'
          };
          const app = initializeApp(firebaseConfig);
          const db = getFirestore(app);
          const analytics = getAnalytics(app);
          export { db };" > src/firebaseConfig.ts

      - name: Build
        run: npm run build -- --no-eslint
